galaxy_info:
  author: google
  description: Munin monitoring server for Ubuntu.
  company: your company (optional)

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2


  platforms:
    - name: Ubuntu
      versions:
      - all


  galaxy_tags: []

dependencies: []
